import { CertificationType } from "@/@types";
import { GITHUB_URL } from ".";

export const CERIFICATIONS: CertificationType[] = [
  {
    id: "1",
    title: "React.js(Basics)",
    description: "I completed my react.js basics assessment from Hackerrank",
    certificate: "https://www.hackerrank.com/certificates/9b1b1f9e1b5d",
    date: "09 Sept, 2022",
    icon: "hr.png",
    logo: "hr_logo.png",
    image: "react.png",
  },
  {
    id: "2",
    title: "Basics of web",
    description: "I completed my Basics of web course from Codedamn.",
    date: "15th Aug, 2022",
    certificate: "https://codedamn.com/certificates/1b1b1f9e1b5d",
    icon: "codedamn.png",
    logo: "codedamn_logo.png",
    image: "basics_of_web.png",
  },
  {
    id: "3",
    title: "Learn Basic js",
    description: "I completed my Basics of Js course from Codedamn.",
    date: "15th Aug, 2022",
    certificate: "https://codedamn.com/certificates/1b1b1f9e1b5d",
    icon: "codedamn.png",
    logo: "codedamn_logo.png",
    image: "basic_js.png",
  },
  {
    id: "4",
    title: "Learn Basic HTML, CSS",
    description: "I completed my Basics of html,css course from Codedamn.",
    date: "15th Aug, 2022",
    certificate: "https://codedamn.com/certificates/1b1b1f9e1b5d",
    icon: "codedamn.png",
    logo: "codedamn_logo.png",
    image: "html_css.png",
  },
  {
    id: "5",
    title: "Learn Next.js 11",
    description: "I completed my Next.js 11 course from Codedamn.",
    date: "16th Aug, 2022",
    certificate: "https://codedamn.com/certificates/1b1b1f9e1b5d",
    icon: "codedamn.png",
    logo: "codedamn_logo.png",
    image: "nextjs.png",
  },
  {
    id: "6",
    title: "Learn Node.js",
    description: "I completed my Basics of web course from Codedamn.",
    date: "Dec, 2022",
    project: GITHUB_URL,
    icon: "udemy.png",
    logo: "udemy_logo.png",
    image: "nodejs.png",
  },
  {
    id: "7",
    title: "Learn React.js",
    description:
      "I completed my Basics of web course from Youtube codevolution channel.",
    date: "Dec, 2022",
    project: GITHUB_URL,
    icon: "utube.png",
    logo: "utube_logo.png",
    image: "react.png",
  },
];
